version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: cs2nades
    restart: always
    env_file:
      - .env

    volumes:
      - ./var/data/:/var/lib/postgresql/data/
